---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
  - name: bretfisher/wordsmith-api
    newName: ghcr.io/larsoleruben-automate-deployments/wordsmith-api
    newTag: stable-20230714-19edc07
  - name: bretfisher/wordsmith-web
    newName: ghcr.io/larsoleruben-automate-deployments/wordsmith-web
    newTag: stable-20230714-4b6ffdf
configMapGenerator:
  - name: db-schema
    files:
      - words.sql
